---
groups:
  - group_name: dev_group 
    servers:
      - name: dev
        type: master
        box: geerlingguy/centos7
        memory: 6144
        ip: 10.0.20.10
        synced_folders: 
          - { guest: "./server", host: "/home/vagrant/server" }
        forwarded_ports:
          - { guest: 50000, host: 50000 } # db2 port
          - { guest: 9080, host: 9080 } # websphere http port
          - { guest: 9443, host: 9443 } # websphere https port
          - { guest: 1414, host: 1414 } # websphere mq port

